### Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "gomaamostafa26@gmail.com",
    "password": "123456789A"
}

### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "gomaamostafa261@gmail.com",
    "password": "123456789A" 
}

### Sign out
POST http://localhost:3000/auth/signout

### GET me
GET http://localhost:3000/auth/me

### GET all users
GET http://localhost:3000/auth?email=gomaamostafa26@gmail.com


### Find User with particular user with given id
GET http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/20
Content-Type: application/json

{
    "email": "gomaa@email.com"
}

### Delete user with ID
DELETE http://localhost:3000/auth/5
