### Create a new valid user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "gomaamostafa26@gmail.com",
    "password": "123456789"
}

### Create a new invalid user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "gomaamostafa26@gmail.com",
    "password": "123456789", "AAA": "MHSA"
}